name: Daily Stock Market Analysis

on:
  schedule:
    - cron: '0 16 * * 1-5'  # Every weekday at 4:00 PM UTC (~11 AM EST)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas matplotlib lxml

    - name: Run stock analyzer
      run: |
        python analyze_market.py
    
    - name: Commit results
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add daily_market_trend.png
        git commit -m "Daily chart update"
        git push
